{
 "title": "My App Dashboard",
 "tags": [ "devops2" ],
 "panels": [
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}